project:
  type: website

website:
  title: "Obstretrics & Gynaecology Dashboard"
  navbar:
    left:
      - href: index.qmd
        text: Documentation
      - href: queries.qmd
        text: "Queries and abbreviations"
      - href: contact.qmd
        text: Contact

format:
  html:
    theme:
      - cosmo
      - brand
    css: stylefiles/documentation.scss
    toc: true