project:
  type: website
  render: 
    - index.qmd
    - queries.qmd
    - contact.qmd

website:
  title: "Obstretrics & Gynaecology Dashboard"
  navbar:
    left:
      - href: index.qmd
        text: Documentation
      - href: queries.qmd
        text: "Queries and abbreviations"
      - href: contact.qmd
        text: Contact

format:
  html:
    theme:
      - cosmo
    css: stylefiles/documentation.scss
    toc: true
    code-overflow: wrap
    resources:
      - stylefiles/documentation.scss